### ISSUE TITLE
Install Rtools on computer FAIL

### ISSUE THREAD

**Issue by DrFletch** [uncoast-unconf/uu-2019#18]
@ijlyttle hope you can help.... got my devtools and git installed okay but when I ran "devtools::has_devel(debug = TRUE) command to install the additional Rtools on my computer I got the following error (see screenshot). Any ideas? 

![image](https://user-images.githubusercontent.com/47152428/55512284-579b8000-5628-11e9-9205-b836f534d4e0.png)

**Comment by srvanderplas** [comment]
Do you have admin access to your machine? If not, you may have to get
someone to install it for you. If you do, see if it works once all R
instances are closed. Failing that, try running the executable with admin
permissions.

**Comment by ijlyttle** [comment]
Building off of @srvanderplas' advice, if you do need to make an adminstrative installation, I might suggest the following: 

- as admin, uninstall any existing Rtools installation; these might be in `C:\RTools` or `C:\RBuildTools`
- download RTools version **3.4** (I have had bad luck manually installing version 3.5) [link to download page](https://cran.r-project.org/bin/windows/Rtools/)
- as admin, with install the RTools you just downloaded

All being well, you should be able to run `devtools::has_devel(debug = TRUE)`, and have it return silently.

Hope this helps!

**Comment by DrFletch** [comment]
@ijlyttle @srvanderplas thank you for your help! There are varying IT security levels here at state government ;) However, I believe I was able to get this installed correctly? Here is a screenshot. 

![image](https://user-images.githubusercontent.com/47152428/55559209-5c594600-56b3-11e9-919a-5dd4e643b5ad.png)

**Comment by srvanderplas** [comment]
It's probably better to check by running this in R: `system('g++ -v')` -
that will display the compiler version, so if you get a bunch of gibberish
back out that looks like what's below, you're probably good to go.

Using built-in specs.
> COLLECT_GCC=C:\PROGRA~1\R\R-34~1.3\library\Rtools\mingw_32\bin\G__~1.EXE
> COLLECT_LTO_WRAPPER=C:/PROGRA~1/R/R-34~1.3/library/Rtools/mingw_32/bin/../libexec/gcc/i686-w64-mingw32/4.9.3/lto-wrapper.exe
> Target: i686-w64-mingw32 Configured with: ../../../src/gcc-4.9.3/configure
> --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32
> --prefix=/mingw32
> --with-sysroot=/home/Jeroen/mingw-gcc-4.9.3/i686-493-posix-dwarf-rt_v3-s/mingw32
> --with-gxx-include-dir=/mingw32/i686-w64-mingw32/include/c++
> --enable-static --disable-shared --disable-multilib
> --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes
> --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto
> --enable-graphite --enable-checking=release --enable-fully-dynamic-string
> --enable-version-specific-runtime-libs --disable-sjlj-exceptions
> --with-dwarf2 --disable-isl-version-check --disable-cloog-version-check
> --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap
> --disable-rpath --disable-win32-registry --disable-nls --disable-werror
> --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=i686
> --with-tune=generic --with-libiconv --with-system-zlib
> --with-gmp=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-w64-mingw32-static
> --with-mpfr=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-w64-mingw32-static
> --with-mpc=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-w64-mingw32-static
> --with-isl=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-w64-mingw32-static
> --with-cloog=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-w64-mingw32-static
> --enable-cloog-backend=isl --with-pkgversion='i686-posix-dwarf, Built by
> MinGW-W64 project' --with-bugurl=http://sourceforge.net/projects/mingw-w64
> CFLAGS='-O2 -pipe
> -I/home/Jeroen/mingw-gcc-4.9.3/i686-493-posix-dwarf-rt_v3-s/mingw32/opt/include
> -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-zlib-static/include
> -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-w64-mingw32-static/include'
> CXXFLAGS='-O2 -pipe
> -I/home/Jeroen/mingw-gcc-4.9.3/i686-493-posix-dwarf-rt_v3-s/mingw32/opt/include
> -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-zlib-static/include
> -I/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-w64-mingw32-static/include'
> CPPFLAGS= LDFLAGS='-pipe
> -L/home/Jeroen/mingw-gcc-4.9.3/i686-493-posix-dwarf-rt_v3-s/mingw32/opt/lib
> -L/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-zlib-static/lib
> -L/home/Jeroen/mingw-gcc-4.9.3/prerequisites/i686-w64-mingw32-static/lib
> -Wl,--large-address-aware' Thread model: posix gcc version 4.9.3
> (i686-posix-dwarf, Built by MinGW-W64 project)


There are a few more `system()` commands to run in this stackoverflow post:
https://stackoverflow.com/questions/48137891/install-rtools-and-check-if-i-can-use-it
that
will check other components if you're paranoid :).

**Comment by ijlyttle** [comment]
Hi @DrFletch,

I yield to @srvanderplas' experience on Rtools and Windows, but I'm curious - does `devtools::has_devel(debug = TRUE)` return silently for you now?

**Comment by DrFletch** [comment]
@srvanderplas @ijlyttle Yes, `devtools::has_devel(debug = TRUE)` returns silently for me now and I also used the system command above to get a bunch of gibberish back. Thank you!

**Comment by srvanderplas** [comment]
Awesome! Rtools + windows is sometimes a real bear, so I'm glad it's
working!

**Comment by dshadravan** [comment]
When I attempt to install Rtools I get this message:

install.packages("rtools")
Installing package into ‘/Users/dshadravan/Library/R/3.5/library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘rtools’ is not available (for R version 3.5.1)

Thoughts?

**Comment by dshadravan** [comment]
FYI - for Mac users, the recommendation (see link below) is to install Xcode.  https://www.rstudio.com/products/rpackages/devtools/
