### ISSUE TITLE
Anyone travelling from Ames to Des Moines for Unconf each day?

### ISSUE THREAD

**Issue by cvanpay** [uncoast-unconf/uu-2019#22]
That I could meet on campus or somewhere central to carpool with you? I will pay for gas! My wife needs our car tomorrow for a Doctor's appointment. I realize this is pretty last minute, so I apologize. If it doesn't work, we will try something else!

Thanks,

Craig

**Comment by cvanpay** [comment]
Also is there a better place to post this to get better visibility?

**Comment by shelmich** [comment]
I'll make a comment to those in attendance at the Day-0 prep

**Comment by srvanderplas** [comment]
Craig - shoot me an email (srvanderplas@gmail.com) and we can figure out where to meet :)

@gzt is riding with me too, so we'll have a party. Just have to figure out where to meet.
